# Permalinks
permalink:           pretty

# Setup
title:               Lauren Jennings
tagline:             Designer at Et Eais
url:                 
baseurl:             http://beinglauren.github.io

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Lauren Jennings
  url:               https://instagram.com/beinglauren
  email:             zdsnider@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/beinglauren/beinglauren

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
